version: "3.8"

services:
  # Express.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CORS_ORIGIN=*
      - MONGODB_URL=mongodb+srv://shivamsingh175503:Shivam123@cluster0.gscplb5.mongodb.net
      - REDIS_HOST=redis-12418.c8.us-east-1-3.ec2.redns.redis-cloud.com
      - REDIS_PORT=12418
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=WrLakliF1v5QhDTv9O6pRIsorsVE0hz7
    networks:
      - app-network

networks:
  app-network:
    external: true
