version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true
